name: Packer Validation and Formatting Check

on:
  push:
    branches:
      - ami-feature1

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Create Application Artifact
        run: |
         mkdir artifacts
         zip -r artifacts/webapp.zip .

      - name: Install Packer
        run: |
          PACKER_VERSION="1.9.4"  # specify your desired version
          wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
          unzip packer_${PACKER_VERSION}_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer --version

      - name: Initialize Packer
        run: packer init debian12.pkr.hcl

      - name: Validate Packer Template
        run: packer validate debian12.pkr.hcl

      - name: Check Packer Template Formatting
        run: |
          if ! packer fmt -check debian12.pkr.hcl; then
            echo "Packer template is not formatted correctly. Please format using 'packer fmt debian12.pkr.hcl' and re-push."
            exit 1
          fi
